import math
import numpy
import matplotlib.pyplot
from matplotlib.ticker import (AutoMinorLocator, MultipleLocator)

data = \
  numpy.loadtxt(
    #"/home/iwtm36/iwtm36/gCP/results/final_report/250_15Ep3_1Em2_1_10/homogenization.txt",
    "/home/iwtm36/iwtm36/gCP/results/linear_displacement/250_15Ep3_1Em2_1_10/homogenization.txt",
    #"/home/iwtm36/Documents/repositories/gCP/results/Tests/no_decohesion_no_slips/homogenization.txt",
    #"/home/iwtm36/Documents/repositories/gCP/results/SPP2013/homogenization.txt",
    delimiter="|", usecols = numpy.arange(1,30), skiprows = 1)
"""
fig, axs = matplotlib.pyplot.subplots(4,7)

axs[0,0].plot(data[:,0], data[:,1], label='Von-Mises Stress')
axs[0,0].legend()
axs[0,0].set(xlabel = "t", ylabel = "Stress")
axs[0,1].plot(data[:,0], data[:,5], label='Stress (11)')
axs[0,1].legend()
axs[0,1].set(xlabel = "t", ylabel = "Stress")
axs[0,2].plot(data[:,0], data[:,6], label='Stress (22)')
axs[0,2].legend()
axs[0,2].set(xlabel = "t", ylabel = "Stress")
axs[0,3].plot(data[:,0], data[:,7], label='Stress (33)')
axs[0,3].legend()
axs[0,3].set(xlabel = "t", ylabel = "Stress")
axs[0,4].plot(data[:,0], data[:,8], label='Stress (23)')
axs[0,4].legend()
axs[0,4].set(xlabel = "t", ylabel = "Stress")
axs[0,5].plot(data[:,0], data[:,9], label='Stress (13)')
axs[0,5].legend()
axs[0,5].set(xlabel = "t", ylabel = "Stress")
axs[0,6].plot(data[:,0], data[:,10], label='Stress (12)')
axs[0,6].legend()
axs[0,6].set(xlabel = "t", ylabel = "Stress")

axs[1,0].plot(data[:,0], data[:,3], label='Von-Mises Strain')
axs[1,0].legend()
axs[1,0].set(xlabel = "t", ylabel = "Strain")
axs[1,1].plot(data[:,0], data[:,11], label='Strain (11)')
axs[1,1].legend()
axs[1,1].set(xlabel = "t", ylabel = "Strain")
axs[1,2].plot(data[:,0], data[:,12], label='Strain (22)')
axs[1,2].legend()
axs[1,2].set(xlabel = "t", ylabel = "Strain")
axs[1,3].plot(data[:,0], data[:,13], label='Strain (33)')
axs[1,3].legend()
axs[1,3].set(xlabel = "t", ylabel = "Strain")
axs[1,4].plot(data[:,0], data[:,14], label='Strain (23)')
axs[1,4].legend()
axs[1,4].set(xlabel = "t", ylabel = "Strain")
axs[1,5].plot(data[:,0], data[:,15], label='Strain (13)')
axs[1,5].legend()
axs[1,5].set(xlabel = "t", ylabel = "Strain")
axs[1,6].plot(data[:,0], data[:,16], label='Strain (12)')
axs[1,6].legend()
axs[1,6].set(xlabel = "t", ylabel = "Strain")

axs[2,0].plot(data[:,0], data[:,2], label='Von-Mises Stress Fluctuations')
axs[2,0].legend()
axs[2,0].set(xlabel = "t", ylabel = "Stress")
axs[2,1].plot(data[:,0], data[:,17], label='Stress (11)')
axs[2,1].legend()
axs[2,1].set(xlabel = "t", ylabel = "Stress")
axs[2,2].plot(data[:,0], data[:,18], label='Stress (22)')
axs[2,2].legend()
axs[2,2].set(xlabel = "t", ylabel = "Stress")
axs[2,3].plot(data[:,0], data[:,19], label='Stress (33)')
axs[2,3].legend()
axs[2,3].set(xlabel = "t", ylabel = "Stress")
axs[2,4].plot(data[:,0], data[:,20], label='Stress (23)')
axs[2,4].legend()
axs[2,4].set(xlabel = "t", ylabel = "Stress")
axs[2,5].plot(data[:,0], data[:,21], label='Stress (13)')
axs[2,5].legend()
axs[2,5].set(xlabel = "t", ylabel = "Stress")
axs[2,6].plot(data[:,0], data[:,22], label='Stress (12)')
axs[2,6].legend()
axs[2,6].set(xlabel = "t", ylabel = "Stress")

axs[3,0].plot(data[:,0], data[:,4], label='Von-Mises Strain Fluctuations')
axs[3,0].legend()
axs[3,0].set(xlabel = "t", ylabel = "Strain")
axs[3,1].plot(data[:,0], data[:,23], label='Strain (11)')
axs[3,1].legend()
axs[3,1].set(xlabel = "t", ylabel = "Strain")
axs[3,2].plot(data[:,0], data[:,24], label='Strain (22)')
axs[3,2].legend()
axs[3,2].set(xlabel = "t", ylabel = "Strain")
axs[3,3].plot(data[:,0], data[:,25], label='Strain (33)')
axs[3,3].legend()
axs[3,3].set(xlabel = "t", ylabel = "Strain")
axs[3,4].plot(data[:,0], data[:,26], label='Strain (23)')
axs[3,4].legend()
axs[3,4].set(xlabel = "t", ylabel = "Strain")
axs[3,5].plot(data[:,0], data[:,27], label='Strain (13)')
axs[3,5].legend()
axs[3,5].set(xlabel = "t", ylabel = "Strain")
axs[3,6].plot(data[:,0], data[:,28], label='Strain (12)')
axs[3,6].legend()
axs[3,6].set(xlabel = "t", ylabel = "Strain")
"""

fig, axs = matplotlib.pyplot.subplots(2,7)

axs[0,0].plot(data[:,0], data[:,1], label='Von-Mises Stress')
axs[0,0].legend()
axs[0,0].set(xlabel = "t", ylabel = "Stress")
axs[0,1].plot(data[:,0], data[:,5], label='Stress (11)')
axs[0,1].legend()
axs[0,1].set(xlabel = "t", ylabel = "Stress")
axs[0,2].plot(data[:,0], data[:,6], label='Stress (22)')
axs[0,2].legend()
axs[0,2].set(xlabel = "t", ylabel = "Stress")
axs[0,3].plot(data[:,0], data[:,7], label='Stress (33)')
axs[0,3].legend()
axs[0,3].set(xlabel = "t", ylabel = "Stress")
axs[0,4].plot(data[:,0], data[:,8], label='Stress (23)')
axs[0,4].legend()
axs[0,4].set(xlabel = "t", ylabel = "Stress")
axs[0,5].plot(data[:,0], data[:,9], label='Stress (13)')
axs[0,5].legend()
axs[0,5].set(xlabel = "t", ylabel = "Stress")
axs[0,6].plot(data[:,0], data[:,10], label='Stress (12)')
axs[0,6].legend()
axs[0,6].set(xlabel = "t", ylabel = "Stress")

axs[1,0].plot(data[:,0], data[:,3], label='Von-Mises Strain')
axs[1,0].legend()
axs[1,0].set(xlabel = "t", ylabel = "Strain")
axs[1,1].plot(data[:,0], data[:,11], label='Strain (11)')
axs[1,1].legend()
axs[1,1].set(xlabel = "t", ylabel = "Strain")
axs[1,2].plot(data[:,0], data[:,12], label='Strain (22)')
axs[1,2].legend()
axs[1,2].set(xlabel = "t", ylabel = "Strain")
axs[1,3].plot(data[:,0], data[:,13], label='Strain (33)')
axs[1,3].legend()
axs[1,3].set(xlabel = "t", ylabel = "Strain")
axs[1,4].plot(data[:,0], data[:,14], label='Strain (23)')
axs[1,4].legend()
axs[1,4].set(xlabel = "t", ylabel = "Strain")
axs[1,5].plot(data[:,0], data[:,15], label='Strain (13)')
axs[1,5].legend()
axs[1,5].set(xlabel = "t", ylabel = "Strain")
axs[1,6].plot(data[:,0], data[:,16], label='Strain (12)')
axs[1,6].legend()
axs[1,6].set(xlabel = "t", ylabel = "Strain")

matplotlib.pyplot.show()
