name: CI

# Controls when the action will run. 
on:
  # Runs on every push on master branch. If a push contains multiple commits, it will be ran on the latest one.
  push:
  pull_request:

env:
  COMPILE_JOBS: 2
  MULTI_CORE_TESTS_REGEX: "mpirun=2"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    name: Build (${{ matrix.build_type }}-deal.ii:${{ matrix.dealii_version }})
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        build_type: ["Release", "Debug"]
        dealii_version: ["v9.3.0"]
    
    # Run steps inside dealii container
    container:
      image: dealii/dealii:${{ matrix.dealii_version }}-focal

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup
        run: |
          # Github action require containers to run as root. We can't do this without breaking the mpi tests.
          # To allow the checkout action to operate, we preemptively give access to the workspace directory manually. 
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE
          # Since dealii image doesn't include Node.js, we'll install it
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends nodejs
          echo "Github actions is sane!"
          echo "Running ${{ matrix.build_type }} build with deal.ii version ${{ matrix.dealii_version }} on branch ${GITHUB_REF#refs/heads/}"
      # Only on PR
      - uses: actions/first-interaction@v1
        if: ${{ github.event_name == 'pull_request' }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Hello, thanks for opening your first issue. Welcome you to the community!'
          pr-message: 'Hello, thanks for opening your first Pull Request and taking the time to improve this library.'

      # Checks-out repository with branch of triggering commit
      - name: Checkout code
        uses: actions/checkout@v2

      # Compile the library
      - name: Compile library (${{ matrix.build_type }}-deal.ii:${{ matrix.dealii_version }})
        run: |
          mkdir build
          cd build
          cmake ../ -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          make -j${{ env.COMPILE_JOBS }}# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
